#
# Copyright (C) 2021 Grakn Labs
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

config:
  version-candidate: VERSION
  dependencies:
    dependencies: [build]

build:
  quality:
    filter:
      owner: graknlabs
      branch: master
    dependency-analysis:
      image: graknlabs-ubuntu-20.04
      command: |
        bazel run @graknlabs_dependencies//grabl/analysis:dependency-analysis
  correctness:
    build:
      image: graknlabs-ubuntu-20.04
      #NPM packages can't be built under RBE
      command: |
        bazel build //...
        bazel run @graknlabs_dependencies//tool/checkstyle:test-coverage
        bazel test $(bazel query 'kind(checkstyle_test, //...)')
    build-dependency:
      image: graknlabs-ubuntu-20.04
      command: |
        dependencies/maven/update.sh
        git diff --exit-code dependencies/maven/artifacts.snapshot
        bazel run @graknlabs_dependencies//tool/unuseddeps:unused-deps -- list
    deploy-maven-snapshot:
      filter:
        owner: graknlabs
        branch: master
      image: graknlabs-ubuntu-20.04
      dependencies: [build, build-dependency]
      command: |
        export DEPLOY_MAVEN_USERNAME=$REPO_GRAKN_USERNAME
        export DEPLOY_MAVEN_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run --define version=$(git rev-parse HEAD) //grpc/java:deploy-maven -- snapshot
    deploy-npm-snapshot:
      filter:
        owner: graknlabs
        branch: master
      image: graknlabs-ubuntu-20.04
      command: |
        curl https://cli-assets.heroku.com/apt/release.key | sudo apt-key add -
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo apt update -y
        sudo apt install -y expect
        export DEPLOY_NPM_USERNAME=$REPO_GRAKN_USERNAME
        export DEPLOY_NPM_PASSWORD=$REPO_GRAKN_PASSWORD
        export DEPLOY_NPM_EMAIL=$REPO_GRAKN_EMAIL
        bazel run --define version=$(git rev-parse HEAD) //grpc/nodejs:deploy-npm -- snapshot
      dependencies: [build, build-dependency]
    deploy-pip-snapshot:
      filter:
        owner: graknlabs
        branch: master
      image: graknlabs-ubuntu-20.04
      type: foreground
      command: |
        pyenv global 3.6.10
        sudo unlink /usr/bin/python3
        sudo ln -s $(which python3) /usr/bin/python3
        sudo ln -s /usr/share/pyshared/lsb_release.py /opt/pyenv/versions/3.6.10/lib/python3.6/site-packages/lsb_release.py
        export DEPLOY_PIP_USERNAME=$REPO_GRAKN_USERNAME
        export DEPLOY_PIP_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run --define version=$(git rev-parse HEAD) //grpc/python:deploy-pip -- snapshot

release:
  filter:
    owner: graknlabs
    branch: master
  deployment:
    deploy-github:
      image: graknlabs-ubuntu-20.04
      command: |
        pip install certifi
        export RELEASE_NOTES_TOKEN=$REPO_GITHUB_TOKEN
        bazel run @graknlabs_dependencies//tool/release:create-notes -- protocol $(cat VERSION) ./RELEASE_TEMPLATE.md
        export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
        bazel run --define version=$(cat VERSION) //:deploy-github -- $GRABL_COMMIT
    deploy-maven-release:
      image: graknlabs-ubuntu-20.04
      command: |
        export DEPLOY_MAVEN_USERNAME=$REPO_GRAKN_USERNAME
        export DEPLOY_MAVEN_PASSWORD=$REPO_GRAKN_PASSWORD
        bazel run --define version=$(cat VERSION) //grpc/java:deploy-maven -- release
      dependencies: [deploy-github]
    deploy-npm-release:
      image: graknlabs-ubuntu-20.04
      command: |
        curl https://cli-assets.heroku.com/apt/release.key | sudo apt-key add -
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo apt update -y
        sudo apt install -y expect
        export DEPLOY_NPM_USERNAME=$REPO_NPM_USERNAME
        export DEPLOY_NPM_PASSWORD=$REPO_NPM_PASSWORD
        export DEPLOY_NPM_EMAIL=$REPO_GRAKN_EMAIL
        bazel run --define version=$(cat VERSION) //grpc/nodejs:deploy-npm -- release
      dependencies: [deploy-github]
    deploy-pip-release:
      image: graknlabs-ubuntu-20.04
      command: |
        pyenv global 3.6.10
        sudo unlink /usr/bin/python3
        sudo ln -s $(which python3) /usr/bin/python3
        sudo ln -s /usr/share/pyshared/lsb_release.py /opt/pyenv/versions/3.6.10/lib/python3.6/site-packages/lsb_release.py
        export DEPLOY_PIP_USERNAME=$REPO_PYPI_USERNAME
        export DEPLOY_PIP_PASSWORD=$REPO_PYPI_PASSWORD
        bazel run --define version=$(cat VERSION) //grpc/python:deploy-pip -- release
      dependencies: [deploy-github]
